# Generated by Django 3.1.5 on 2021-01-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210117_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='age',
            field=models.IntegerField(default=20, verbose_name='나이'),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='birth_day',
            field=models.DateField(null=True, verbose_name='생년월일'),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='email',
            field=models.CharField(default=False, max_length=255, verbose_name='이메일 주소'),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='gender',
            field=models.CharField(default='male', max_length=6, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='name',
            field=models.CharField(default=False, max_length=20, verbose_name='이름'),
        ),
    ]
